# Generated by Django 4.2.3 on 2023-07-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Brand New', 'BRAND NEW'), ('Refurbished', 'REFURBISHED'), ('Used', 'USED')], default='Brand New', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
