# Generated by Django 4.2.3 on 2023-07-12 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_amountpaid_levels_passwordresets_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('student_number', models.CharField(default='hsa/0000/A', max_length=300)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('nationality', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], default='MALE', max_length=10)),
                ('image', models.ImageField(default='images/pic.png', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='amountpaid',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.students'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
